import Foundation

/// Payload written to `data.js` as `window.ZC_DATA = {...};`.
public struct WebPayload: Codable, Sendable {
    public struct PinNode: Codable, Sendable {
        public let id: String
        public let text: String
        public let author: String
        public let work: String
        public let themes: [String]
        public let tags: [String]
        public let pinnedAt: String
    }

    public struct AuthorNode: Codable, Sendable {
        public let name: String
        public let pinCount: Int
    }

    public struct WorkNode: Codable, Sendable {
        public let author: String
        public let title: String
        public let pinCount: Int
        public let quoteCount: Int
    }

    public struct LogRow: Codable, Sendable {
        public let date: String
        public let mood: Int
        public let sleep: Int
        public let strength: Int
        public let stillness: Int
        public let composite: Int
    }

    public struct Point: Codable, Sendable {
        public let date: String
        public let value: Double
    }

    public struct TrajectoryNode: Codable, Sendable {
        public let actual: [Point]
        public let smoothed: [Point]
        public let projection: [Point]
    }

    /// Today's Truth, shown full screen before the constellation on the first open of the day.
    public struct TruthNode: Codable, Sendable {
        public let id: String
        public let text: String
        public let author: String
        public let work: String
    }

    public let generatedAt: String
    public let today: String
    public let truth: TruthNode?
    public let showTruthIntro: Bool
    public let pins: [PinNode]
    public let authors: [AuthorNode]
    public let works: [WorkNode]
    public let recommendations: [Poster]
    public let logs: [LogRow]
    public let trajectory: TrajectoryNode
    public let streak: Int
    public let total: Int
}

public enum WebExport {
    public static func payload(from store: Store, now: Date = Date(), showTruthIntro: Bool = false) throws -> WebPayload {
        let pins = try store.pins(.all).map {
            WebPayload.PinNode(id: $0.quote.id, text: $0.quote.text, author: $0.quote.author, work: $0.quote.work,
                               themes: $0.quote.themes, tags: $0.tags.map(\.name), pinnedAt: $0.pinnedAt)
        }
        let authors = try store.authorPinCounts().map { WebPayload.AuthorNode(name: $0.author, pinCount: $0.pinCount) }
        let works = try store.workPinCounts().map {
            WebPayload.WorkNode(author: $0.author, title: $0.work, pinCount: $0.pinCount, quoteCount: $0.quoteCount)
        }
        let logs = try store.logs()
        let rows = logs.map {
            WebPayload.LogRow(date: $0.date, mood: $0.mood, sleep: $0.sleep, strength: $0.strength,
                              stillness: $0.stillness, composite: $0.composite)
        }
        let result = Trajectory.compute(logs)
        func points(_ list: [TrajectoryPoint]) -> [WebPayload.Point] {
            list.map { WebPayload.Point(date: $0.dateKey, value: $0.value) }
        }
        let trajectory = WebPayload.TrajectoryNode(actual: points(result.actual), smoothed: points(result.smoothed),
                                                   projection: points(result.projection))
        let today = DayKey.key(for: now)
        let truth = try store.truthOfDay(today).map {
            WebPayload.TruthNode(id: $0.id, text: $0.text, author: $0.author, work: $0.work)
        }
        let formatter = ISO8601DateFormatter()
        return WebPayload(generatedAt: formatter.string(from: now), today: today, truth: truth,
                          showTruthIntro: showTruthIntro && truth != nil, pins: pins, authors: authors, works: works,
                          recommendations: try store.recommendations(), logs: rows, trajectory: trajectory,
                          streak: try store.streak(today: DayKey.key(for: now)), total: logs.count)
    }

    /// JavaScript source assigning the payload to `window.ZC_DATA`.
    public static func javascript(for payload: WebPayload) throws -> String {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
        let json = String(data: try encoder.encode(payload), encoding: .utf8) ?? "{}"
        return "// Generated by ZeroCortisol. Do not edit.\nwindow.ZC_DATA = \(json);\n"
    }

    /// Writes `data.js` and a fresh copy of `index.html` into `directory`; returns the index URL.
    @discardableResult
    public static func export(store: Store, indexHTML: URL, to directory: URL, showTruthIntro: Bool = false) throws -> URL {
        let fm = FileManager.default
        try fm.createDirectory(at: directory, withIntermediateDirectories: true)
        let js = try javascript(for: try payload(from: store, showTruthIntro: showTruthIntro))
        try js.write(to: directory.appendingPathComponent("data.js"), atomically: true, encoding: .utf8)
        let target = directory.appendingPathComponent("index.html")
        if fm.fileExists(atPath: target.path) { try fm.removeItem(at: target) }
        try fm.copyItem(at: indexHTML, to: target)
        return target
    }
}
